services:
  searxng:
    image: searxng/searxng
    container_name: searxng
    volumes:
      - ${SEARXNG_CONFIG_FOLDER:-./config}:/etc/searxng
      - ${SEARXNG_DATA_FOLDER:-./data}:/var/cache/searxng
    ports:
      - ${SEARXNG_PORT:-8080}:8080
    restart: unless-stopped
    networks:
      net:

  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      net:
    volumes:
      - ${SEARXNG_REDIS_DATA_FOLDER:-./redis-data}:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  net: {}